#!/bin/bash

set -euo pipefail

help() {
	cat << EOF

Usage: gh combine-prs --query "QUERY"
	Combines multiple PRs into one.

	Required arguments:
		--query "QUERY"
				sets the query used to find combinable PRs.
				e.g. --query "author:app/dependabot"
				to combine Dependabot PRs
	Optional arguments:
		--selected-pr-numbers COMMA,SEPARATED,LIST
				if set, will only work on PRs with the selected numbers.
				e.g. --selected-pr-numbers 42,13,78
				Defaults to selecting every PR matching the QUERY
		--limit LIMIT
				sets the maximum number of PRs that will be combined.
				Defaults to 50
		--skip-pr-check
				if set, will combine matching PRs even if they are not passing checks.
				Defaults to false when not specified
				
		--pr-labels
		                list of tags to assign to the PR
				Defaults to none.

EOF
}

confirm() {
	while read -r -n1 key; do
		if [[ $key == $'\e' ]]; then
			exit 0
		else
			break
		fi
	done
}

LIMIT=50
QUERY=""
SKIP_PR_CHECK="false"
SELECTED_PR_NUMBERS=
PR_LABELS=
while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help)
		help
		exit 0
		;;
	--selected-pr-numbers)
		shift
		SELECTED_PR_NUMBERS=$1
		;;
	--limit)
		shift
		LIMIT=$1
		;;
	--query)
		shift
		QUERY=$1
		;;
	--skip-pr-check)
		SKIP_PR_CHECK="true"
		;;
	--pr-tags
		shift
		PR_LABELS=$1
	*)
		help >&2
		exit 1
		;;
	esac
	shift
done

DEFAULT_BRANCH=$(gh api /repos/:owner/:repo --jq '.default_branch')
COMBINED_BRANCH=pr-train-$(date +%s)
BODY_FILE=/tmp/.combined-pr-body.md

if [[ -z "${QUERY}" ]]; then
	help
	echo "Error: --query is required; e.g. --query \"author:app/dependabot\""
	exit 1
fi

cat <<- EOF > $BODY_FILE
	Combining multiple PRs into one.

	## Combined PRs

EOF

echo "The following PRs will be evaluated for inclusion:"
gh pr list --search "${QUERY}" --limit "${LIMIT}"
if [[ "${SKIP_PR_CHECK}" == "true" ]]; then
	echo -e "\nAction status checks for PRs will be skipped"
fi
JQ_FILTER=".[]"
if [[ -n "${SELECTED_PR_NUMBERS}" ]]; then
	echo -e "\nOnly the following PRs will be selected: $SELECTED_PR_NUMBERS"
	JQ_FILTER="$JQ_FILTER | select(.number == ($SELECTED_PR_NUMBERS))"
fi
echo "Press any key to continue or escape to abort"
confirm

git fetch
git checkout "${DEFAULT_BRANCH}"
git pull --ff-only

git branch -D "$COMBINED_BRANCH" || true
git checkout -b "$COMBINED_BRANCH"

count=0
gh pr list --search "${QUERY}" --limit "${LIMIT}" --json headRefName,number | jq -r "$JQ_FILTER | [.number,.headRefName] | @tsv" | while read -r NUMBER HEADREF
do
	if [[ "${SKIP_PR_CHECK}" == "false" ]] && [[ $(gh pr checks "$NUMBER" | cut -d$'\t' -f2 | grep -E "fail|pending" -c) -gt 0 ]]; then
		echo "Not all checks are passing - skipping PR #$NUMBER"
		continue
	fi

	echo "Trying to merge $HEADREF into $COMBINED_BRANCH"
	if [[ ! $(git merge "origin/$HEADREF" --no-edit) ]]; then
		echo "Unable to merge $HEADREF - skipping PR #$NUMBER"
		git merge --abort
		continue
	fi
	echo "Merged $HEADREF (#$NUMBER) into $COMBINED_BRANCH"

	DESCRIPTION=$(gh pr view "$NUMBER" --json title,author,number --template '{{.title}} (#{{.number}}) @{{.author.login}}')
	echo "* ${DESCRIPTION}" >> $BODY_FILE

	((count=count+1))
	if [[ $count == "$LIMIT" ]]; then
		echo "Hit limit of $LIMIT - no more PRs will be added"
		break
	fi
done

echo -e "Preview of PR:\n\n"
cat $BODY_FILE

echo -e "\n\nFinished merging - press any key to create PR or escape to abort"
confirm

echo "Creating PR"
gh pr create --title "Combined PR" --body-file $BODY_FILE --label "$PR_LABELS"
